### ISSUE TITLE
Machine Translation Evaluation Metrics

### ISSUE THREAD

**Issue by ilkerkesen** [JuliaML/MLMetrics.jl#17]
I have a BLEU implementation in Julia and I'm going to implement other machine translation evaluation metrics (cider, meteor etc.) as well. Would you like those implementations being a part of this package?

**Comment by Evizero** [comment]
I think in principle this would be the right place.

This package is a bit in limbo (because of me), so I still need to do a lot of cleanup. Quite a few backend things that are here already moved to other (actively maintained) packages. So I am unsure if it even compiles currently.

Maybe a good course of action would be to make a stand-alone `MLTranslationMetrics` package. We could move (or simply reexport) that code later on.

**Comment by ilkerkesen** [comment]
Okay then. Let's talk again when I'll have implemented those metrics. Thanks!

**Comment by Ayushk4** [comment]
Is there any implementation of ROUGE and METEOR in julia?
